### ISSUE TITLE
Is it possible to use vscroll without viewport?

### ISSUE THREAD

**Issue by nclemeur** [dhilt/vscroll#45]
I am thinking at using vscroll to implement virtual scrolling on an html table. The problem is that with the current structure there is 2 levels of html elements before reaching an item (the viewport and the vscroll). I would like to only scroll the rows from the tbody in my table. So the scrollable area is the tbody, while each rows are "items". So I am not really sure how to setup the viewport in that case?

I have tried to use vue example as a starting point to remove the viewport (in that case I had viewport==element), but that did not work really well (initial rendering shows only 4 "items", scrolling make this others appear but the scrollbar seems to have the wrong information about the size... So is it possible to achieve this?

It seems that this should be feasible, but something is not quite right... See the screenshots below

Please let me know if I am missing something, or if something is not clear in my description

Initial view (see how the scrollbar thumb is quite big):
![image](https://user-images.githubusercontent.com/7132890/235063817-df7dc641-4df5-4449-b259-0eb0d42ee4de.png)
After a little bit of scrolling:
![image](https://user-images.githubusercontent.com/7132890/235063889-4226aee3-ad59-4e6a-ab76-c646003c71ce.png)
More scrolling:
![image](https://user-images.githubusercontent.com/7132890/235064001-99b115f4-4d3e-41fb-9063-abdf860d4765.png)
And it can go pass the end
![image](https://user-images.githubusercontent.com/7132890/235064049-5c3d4339-005d-4961-8110-a309ed97723a.png)

**Comment by dhilt** [comment]
@nclemeur Viewport is essential and must present. Fortunately, we have some customization facilities. The first one is the [viewportElement settings](https://dhilt.github.io/ngx-ui-scroll/#/experimental#viewportElement-setting), which allow you to set an element other than the nearest HTML element as the viewport. Say, we have the following html:

```html
<div id="viewport" style="height: 150px; overflow-y: scroll">
  <table>
    <thead>
      <tr><th>Num</th><th>Text</th></tr>
    </thead>
    <tbody id="vscroll">
      <tr data-padding-backward><td colspan="2"></td></tr>
      <!-- vscroll rows -->
      <tr data-padding-forward><td colspan="2"></td></tr>
    </tbody>
  </table>
</div>
```

Instead of default `table` (which is nearest to the "vscroll" element) we may use the outer `div` as the viewport:

```js
const datasource = {
  get: ...,
  settings: {
    ...
    viewportElement: () => document.getElementById('viewport'),
  },
}
```

Another issue is that the `thead` becomes part of the scrollable area. I guess, there might be different ways of handling it, but on the vscroll's end we may use [Routines class](https://github.com/dhilt/vscroll#5-routines) overrides, and provide the offset taken directly from the html:

```js
const workflowParams = {
  element: document.getElementById('vscroll'),
  datasource,
  ...
  Routines: class {
    getOffset() {
      return document.querySelector('#viewport thead')?.offsetHeight || 0;
    }
  }
};
```

I created the demo containing the suggested approach: https://stackblitz.com/edit/vscroll-1-5-3-table. Hope this makes sense.

**Comment by nclemeur** [comment]
Hello Denis,

Thank you very much for the answer. It seems that this is indeed a workable solution. I did modify slightly your example to get the headers to stick to the top and it's working nicely (you can check it [there](https://stackblitz.com/edit/vscroll-1-5-3-table-19zz57?file=index.html). The only modification was to remove the unused css avout `tableFixHead` and add the `position: sticky; top: 0` to the th css. I'll try to integrate that technique in my app and I'll report back if I have any issues. But in all case thank you for the help. 
And sorry to open an issue for what is basically a question, may I suggest to add the discussion feature in github?

**Comment by dhilt** [comment]
@nclemeur Sticky is marvelous, I added the result demo to the repo: https://dhilt.github.io/vscroll/table-demo.html. Also, I added Discussions, though I like that this issue remains an issue.
